server:
  port: 8086

spring:
  application:
    name: HOSPITAL-SERVICE

  datasource:
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/hospital_service_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultUrl: ${EUREKA.URI:http://localhost:8761/eureka/}
    instance:
      preferIpAddress: true

services:
  user-service-url: http://USER-SERVICE/user/
  booking-service-url: http://BOOKING-SERVICE/booking/
  payment-service-url: http://PAYMENT-SERVICE/payment/
  notification-service-url: http://NOTIFICATION-SERVICE/notification/


jwt:
  secret:
    key:  753778214125442A472D4B6150645367566B59703373367639792F423F452848
  access:
    expiry: 3000000
  refresh:
    expiry: 3000000

